# Generated by Django 4.1.5 on 2023-03-22 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(choices=[('Computer Science Engineerning', 'Computer Science Engineerning'), ('Electronics Engineerning', 'Electronics Engineerning'), ('Civil Engineerning', 'Civil Engineerning'), ('Mechanical Engineerning', 'Mechanical Engineerning'), ('Electrical Engineerning', 'Electrical Engineerning')], max_length=255)),
                ('Phone_Number', models.IntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Profile_Image', models.FileField(upload_to='teachers')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
