# Generated by Django 4.1.5 on 2023-03-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='Blood_Group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='Date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
