# Generated by Django 4.1.5 on 2023-03-24 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_studentprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(choices=[('semester 1', 'semester 1'), ('semester 2', 'semester 2'), ('semester 3', 'semester 3'), ('semester 4', 'semester 4'), ('semester 5', 'semester 5'), ('semester 6', 'semester 6')], max_length=255)),
                ('Department', models.CharField(choices=[('Computer Science Engineerning', 'Computer Science Engineerning'), ('Electronics Engineerning', 'Electronics Engineerning'), ('Civil Engineerning', 'Civil Engineerning'), ('Mechanical Engineerning', 'Mechanical Engineerning'), ('Electrical Engineerning', 'Electrical Engineerning')], max_length=255)),
                ('work_type', models.CharField(choices=[('Series Test', 'Series Test'), ('Assignement', 'Assignement'), ('Project', 'Project')], max_length=255)),
                ('work_title', models.CharField(max_length=255)),
                ('Date_assigned', models.DateField(auto_now=True)),
                ('Date_of_Submission', models.DateField()),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(choices=[('semester 1', 'semester 1'), ('semester 2', 'semester 2'), ('semester 3', 'semester 3'), ('semester 4', 'semester 4'), ('semester 5', 'semester 5'), ('semester 6', 'semester 6')], max_length=255)),
                ('Department', models.CharField(choices=[('Computer Science Engineerning', 'Computer Science Engineerning'), ('Electronics Engineerning', 'Electronics Engineerning'), ('Civil Engineerning', 'Civil Engineerning'), ('Mechanical Engineerning', 'Mechanical Engineerning'), ('Electrical Engineerning', 'Electrical Engineerning')], max_length=255)),
                ('Date_assigned', models.DateField(auto_now=True)),
                ('timetable', models.FileField(upload_to='timetable')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(choices=[('semester 1', 'semester 1'), ('semester 2', 'semester 2'), ('semester 3', 'semester 3'), ('semester 4', 'semester 4'), ('semester 5', 'semester 5'), ('semester 6', 'semester 6')], max_length=255)),
                ('Department', models.CharField(choices=[('Computer Science Engineerning', 'Computer Science Engineerning'), ('Electronics Engineerning', 'Electronics Engineerning'), ('Civil Engineerning', 'Civil Engineerning'), ('Mechanical Engineerning', 'Mechanical Engineerning'), ('Electrical Engineerning', 'Electrical Engineerning')], max_length=255)),
                ('Semester_Result', models.FileField(upload_to='semresult')),
                ('Date_assigned', models.DateField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicWorkMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.studentprofile')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.academicwork')),
            ],
        ),
    ]
