# Generated by Django 4.1.5 on 2023-03-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_academicwork_timetable_semesterresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicwork',
            name='total_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
