# Generated by Django 4.1.5 on 2023-03-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_timetable_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Late', 'Late'), ('Absent', 'Absent')], max_length=255)),
                ('Attendance_Date', models.DateField()),
                ('added_date', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.studentprofile')),
            ],
        ),
    ]
