# Generated by Django 4.1.5 on 2023-03-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='added_date',
            new_name='date_taken',
        ),
    ]
