# Generated by Django 4.1.5 on 2023-03-25 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0009_attendance_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('Poem', 'Poem'), ('Story', 'Story'), ('Art', 'Art'), ('Article', 'Article'), ('Other', 'Other')], max_length=255)),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.CharField(max_length=255)),
                ('Image', models.FileField(blank=True, null=True, upload_to='noticeboard')),
                ('uploaded_date', models.DateField(auto_now=True)),
                ('Status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.studentprofile')),
            ],
        ),
    ]
